version: '3'

tasks:
  default:
    desc: Show the available tasks
    cmds:
      - task --list --sort alphanumeric
  
  packer-build:    desc: Build AMI with Packer    cmds:      - |        cd ami        AWS_REGION=$(aws configure get region)        VPC_ID=$(aws ec2 describe-vpcs --query 'Vpcs[0].VpcId' --output text --region $AWS_REGION)        SUBNET_ID=$(aws ec2 describe-subnets --filters "Name=vpc-id,Values=$VPC_ID" "Name=tag:Name,Values=public-*" --query 'Subnets[0].SubnetId' --output text --region $AWS_REGION)        packer build \          -var "aws_region=$AWS_REGION" \          -var "vpc_id=$VPC_ID" \          -var "subnet_id=$SUBNET_ID" \          {{.PACKER_DEBUG}} \          nat-gateway.pkr.hcl  packer-build:debug:    desc: Build AMI with Packer (Debug Mode)    vars:      PACKER_DEBUG: "--debug"    deps:      - packer-build      